name: Check Repos File

on:
  push:
    paths:
      - 'repos.txt'

jobs:
  check_repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH and SCP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          scp /github/workspace/repos.txt /maintenance/repos.txt
          ssh /maintenance/clone_repos.sh "${{ github.actor }}" "${{ secrets.GH_PAT }}"
          ssh /maintenance/start_existing_containers.sh