name: Check Repos File

on:
  push:
    paths:
      - 'repos.txt'

jobs:
  check_repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Wait for 1 minute
      run: sleep 10

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_KEY }}
        known_hosts: ${{ secrets.SERVER_KNOWN_HOSTS }}

    - name: Setup SSH and SCP
      run: |
        scp repos.txt root@${{ secrets.DOCKER_INSTANCE_IP }}:/maintenance/repos.txt
        ssh root@${{ secrets.DOCKER_INSTANCE_IP }} /maintenance/clone_repos.sh "${{ github.actor }}" "${{ secrets.GH_PAT }}"
        ssh root@${{ secrets.DOCKER_INSTANCE_IP }} /maintenance/start_existing_containers.sh