name: Check Repos File

on:
  push:
    paths:
      - 'repos.txt'

jobs:
  check_repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Wait for 1 minute
      run: sleep 10

    - name: Copy repos.txt to the remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DOCKER_INSTANCE_IP }}
        username: root
        key: ${{ secrets.DOCKER_INSTANCE_PRIVATE_KEY }}
        source: "repos.txt"
        target: "/maintenance"
        overwrite: true

    - name: deploy on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_INSTANCE_IP }}
        username: root
        key: ${{ secrets.DOCKER_INSTANCE_PRIVATE_KEY }}
        script: |
          /maintenance/clone_repos.sh "${{ github.actor }}" "${{ secrets.GH_PAT }}"
          /maintenance/start_existing_containers.sh


#    - name: Install SSH key
#      uses: shimataro/ssh-key-action@v2
#      with:
#        key: ${{ secrets.DOCKER_INSTANCE_PRIVATE_KEY }}
#        known_hosts: ${{ secrets.DOCKER_INSTANCE_IP }}
#
#    - name: Setup SSH and SCP
#      run: |
#        scp -o StrictHostKeyChecking=no repos.txt root@${{ secrets.DOCKER_INSTANCE_IP }}:/maintenance/repos.txt
#        ssh root@${{ secrets.DOCKER_INSTANCE_IP }} /maintenance/clone_repos.sh "${{ github.actor }}" "${{ secrets.GH_PAT }}"
#        ssh root@${{ secrets.DOCKER_INSTANCE_IP }} /maintenance/start_existing_containers.sh